---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: python
        files: \.(yml|yaml)$
        args: ["--strict"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdownlint.json"]
